/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rug.icdtools.customdiag;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author hcadavid
 */
public class ExternalCommandRunner {
   
    private static class InputStreamStringBufferReader implements Runnable {

        private BufferedReader input;
        private StringBuffer output;        

        public InputStreamStringBufferReader(BufferedReader input, StringBuffer output) {
            this.input = input;
            this.output = output;
        }

        @Override
        public void run() {
            try {
                String line = null;
                while ((line = input.readLine()) != null) {
                    output.append(line + "\n");                    
                }
            } catch (IOException ex) {
                throw new RuntimeException("Error generated by command reception callback thread.", ex);
            }
        }

    }
    
    
    
    /**
     * 
     * @param command
     * @throws ExternalCommandExecutionException 
     */
    public static void runCommand(String... command) throws ExternalCommandExecutionException {
        try{                        
            ProcessBuilder builder = new ProcessBuilder();
            builder.command(command);                  
            Process process = builder.start();

            final BufferedReader stderrReader = new BufferedReader(new InputStreamReader(process.getErrorStream()));                
            final StringBuffer stderrText = new StringBuffer();

            InputStreamStringBufferReader errReading=new InputStreamStringBufferReader(stderrReader,stderrText);        
            Thread errReadingThread = new Thread(errReading);
            errReadingThread.start();  

            //wait the process, and stderr reader thread to finish
            int exitCode = process.waitFor();        
            errReadingThread.join();
            
            //In some commands, an output on stdin could also mean an error related to wrong arguments (i.e., showing parameters description)
            
            if (exitCode!=0){
                throw new ExternalCommandExecutionException("Command ["+String.join(",",command)+"] returned an error code:"+exitCode+". Error message:"+stderrText.toString());
            }
            if (!stderrText.toString().trim().equals("")) {
                throw new RuntimeException("Command ["+String.join(",",command)+"] returned an error on STDERR:" + stderrText.toString());
            }
        } catch (IOException e){
            throw new ExternalCommandExecutionException("Command ["+String.join(",",command)+"] failed due to an I/O error:"+e.getMessage(),e);
        } catch (InterruptedException ex) {
            throw new ExternalCommandExecutionException("Command ["+String.join(",",command)+"] failed due to an unexpected thread-related error:"+ex);            
        } 
                
    }
    
    
    

    
}


