name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2       
      with:
        submodules: recursive
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}     
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: update sysrdl2jinja submodule
      run: git submodule update --remote
    - name: Build the Docker image        
      run: docker build . --file Dockerfile --tag hectorcadavid/asciidoctor-icd-experimental:v0.2
    - name: Docker push
      run: docker push hectorcadavid/asciidoctor-icd-experimental:v0.2
